name: Syhunt Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: windows-latest  # Alterado para Windows
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Syhunt e rodar o scan
        run: |
          Invoke-WebRequest -Uri "https://www.syhunt.com/download/syhunt-hybrid.exe" -OutFile "syhunt-hybrid.exe"
          Start-Process -FilePath ".\syhunt-hybrid.exe" -ArgumentList "/S" -NoNewWindow -Wait
          & "C:\Program Files\Syhunt\syhuntcli.exe" -t "https://seusite.com" -o "syhunt-report.html"

      - name: Fazer upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: syhunt-report
          path: syhunt-report.html
