name: Syhunt Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Syhunt Scan
        uses: Syhunt/WebAppScan-Action@main
        with:
          target: "https://seusite.com" 
          report_format: "html"  
          output_path: "syhunt-report.html"

      - name: Fazer upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: syhunt-report
          path: syhunt-report.html
