jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Iniciar o servidor local (se necessário)
        run: |
          npm install
          npm start &  # Executa em background

      - name: Rodar Syhunt Scan no localhost
        run: |
          docker run --rm syhunt/webappscan -t "http://localhost:3000" -o "syhunt-report.html"

      - name: Fazer upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: syhunt-report
          path: syhunt-report.html
